name: divoom

services:
  divoom:
    build: .
    image: divoom:latest
    container_name: divoom
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./images:/app/images:ro
      - ./fonts:/app/fonts:ro
      - ./logs:/app/logs
